//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1008
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace RecordingConfigData {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:xmlns:RecordingConfig")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:xmlns:RecordingConfig", IsNullable=false)]
    public partial class RecordingConfig {
        
        private string portalDomainField;
        
        private int portalPortField;
        
        private string portalUserNameField;
        
        private string portalPasswordField;
        
        private string sourceDomainField;
        
        private int sourcePortField;
        
        private int fragmentLengthField;
        
        private int videoProxyPortField;
        
        private int sensitivityField;
        
        private string proxyCommandLineField;
        
        private string recordingCommandLineField;
        
        private bool noAudioField;
        
        public RecordingConfig() {
            this.portalDomainField = "rationalcity.com";
            this.portalPortField = 80;
            this.portalUserNameField = "Administrator";
            this.portalPasswordField = "";
            this.sourceDomainField = "localhost";
            this.sourcePortField = 8081;
            this.fragmentLengthField = 20;
            this.videoProxyPortField = 8080;
            this.sensitivityField = 50;
            this.proxyCommandLineField = "";
            this.recordingCommandLineField = "";
            this.noAudioField = true;
        }
        
        /// <remarks/>
        public string PortalDomain {
            get {
                return this.portalDomainField;
            }
            set {
                this.portalDomainField = value;
            }
        }
        
        /// <remarks/>
        public int PortalPort {
            get {
                return this.portalPortField;
            }
            set {
                this.portalPortField = value;
            }
        }
        
        /// <remarks/>
        public string PortalUserName {
            get {
                return this.portalUserNameField;
            }
            set {
                this.portalUserNameField = value;
            }
        }
        
        /// <remarks/>
        public string PortalPassword {
            get {
                return this.portalPasswordField;
            }
            set {
                this.portalPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SourceDomain {
            get {
                return this.sourceDomainField;
            }
            set {
                this.sourceDomainField = value;
            }
        }
        
        /// <remarks/>
        public int SourcePort {
            get {
                return this.sourcePortField;
            }
            set {
                this.sourcePortField = value;
            }
        }
        
        /// <remarks/>
        public int FragmentLength {
            get {
                return this.fragmentLengthField;
            }
            set {
                this.fragmentLengthField = value;
            }
        }
        
        /// <remarks/>
        public int VideoProxyPort {
            get {
                return this.videoProxyPortField;
            }
            set {
                this.videoProxyPortField = value;
            }
        }
        
        /// <remarks/>
        public int Sensitivity {
            get {
                return this.sensitivityField;
            }
            set {
                this.sensitivityField = value;
            }
        }
        
        /// <remarks/>
        public string ProxyCommandLine {
            get {
                return this.proxyCommandLineField;
            }
            set {
                this.proxyCommandLineField = value;
            }
        }
        
        /// <remarks/>
        public string RecordingCommandLine {
            get {
                return this.recordingCommandLineField;
            }
            set {
                this.recordingCommandLineField = value;
            }
        }
        
        /// <remarks/>
        public bool NoAudio {
            get {
                return this.noAudioField;
            }
            set {
                this.noAudioField = value;
            }
        }
    }
}
