//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace VideoFragmentData {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:xmlns:VideoFragmentManifest")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:xmlns:VideoFragmentManifest", IsNullable=false)]
    public partial class VideoFragmentManifest {
        
        private YouTubeManifestType youTubeManifestField;
        
        private EventDetectorManifestType eventDetectorManifestField;
        
        /// <remarks/>
        public YouTubeManifestType YouTubeManifest {
            get {
                return this.youTubeManifestField;
            }
            set {
                this.youTubeManifestField = value;
            }
        }
        
        /// <remarks/>
        public EventDetectorManifestType EventDetectorManifest {
            get {
                return this.eventDetectorManifestField;
            }
            set {
                this.eventDetectorManifestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:VideoFragmentManifest")]
    public partial class YouTubeManifestType {
        
        private string developerKeyField;
        
        private string userNameField;
        
        private string userPassField;
        
        private string titleField;
        
        private string categoryField;
        
        private string keywordsField;
        
        private string descriptionField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string tagsField;
        
        private bool uploadingSuccessfulField;
        
        private string watchPageField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string DeveloperKey {
            get {
                return this.developerKeyField;
            }
            set {
                this.developerKeyField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserPass {
            get {
                return this.userPassField;
            }
            set {
                this.userPassField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string Category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        public string Keywords {
            get {
                return this.keywordsField;
            }
            set {
                this.keywordsField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Tags {
            get {
                return this.tagsField;
            }
            set {
                this.tagsField = value;
            }
        }
        
        /// <remarks/>
        public bool UploadingSuccessful {
            get {
                return this.uploadingSuccessfulField;
            }
            set {
                this.uploadingSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
        public string WatchPage {
            get {
                return this.watchPageField;
            }
            set {
                this.watchPageField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:VideoFragmentManifest")]
    public partial class EventType {
        
        private string typeField;
        
        private int countField;
        
        private System.DateTime dateRangeFromField;
        
        private System.DateTime dateRangeToField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateRangeFrom {
            get {
                return this.dateRangeFromField;
            }
            set {
                this.dateRangeFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DateRangeTo {
            get {
                return this.dateRangeToField;
            }
            set {
                this.dateRangeToField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:xmlns:VideoFragmentManifest")]
    public partial class EventDetectorManifestType {
        
        private EventType[] eventListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Event", IsNullable=false)]
        public EventType[] EventList {
            get {
                return this.eventListField;
            }
            set {
                this.eventListField = value;
            }
        }
    }
}
