//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("OonzeModel", "TableYouTubeAttributeKeyword", "TableYouTubeAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.TableYouTubeAttribute), "TableYouTubeKeyword", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.TableYouTubeKeyword))]
[assembly: EdmRelationshipAttribute("OonzeModel", "TableYouTubeAttributeTag", "TableYouTubeAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.TableYouTubeAttribute), "TableYouTubeTag", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.TableYouTubeTag))]
[assembly: EdmRelationshipAttribute("OonzeModel", "FK_TableYouTubeAttributes_TableDevice", "TableDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(web.Models.TableDevice), "TableYouTubeAttribute", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(web.Models.TableYouTubeAttribute), true)]

#endregion

namespace web.Models
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class YouTubeEntities : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект YouTubeEntities, используя строку соединения из раздела "YouTubeEntities" файла конфигурации приложения.
        /// </summary>
        public YouTubeEntities() : base("name=YouTubeEntities", "YouTubeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта YouTubeEntities.
        /// </summary>
        public YouTubeEntities(string connectionString) : base(connectionString, "YouTubeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта YouTubeEntities.
        /// </summary>
        public YouTubeEntities(EntityConnection connection) : base(connection, "YouTubeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TableYouTubeAttribute> TableYouTubeAttribute
        {
            get
            {
                if ((_TableYouTubeAttribute == null))
                {
                    _TableYouTubeAttribute = base.CreateObjectSet<TableYouTubeAttribute>("TableYouTubeAttribute");
                }
                return _TableYouTubeAttribute;
            }
        }
        private ObjectSet<TableYouTubeAttribute> _TableYouTubeAttribute;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TableYouTubeKeyword> TableYouTubeKeyword
        {
            get
            {
                if ((_TableYouTubeKeyword == null))
                {
                    _TableYouTubeKeyword = base.CreateObjectSet<TableYouTubeKeyword>("TableYouTubeKeyword");
                }
                return _TableYouTubeKeyword;
            }
        }
        private ObjectSet<TableYouTubeKeyword> _TableYouTubeKeyword;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TableYouTubeTag> TableYouTubeTag
        {
            get
            {
                if ((_TableYouTubeTag == null))
                {
                    _TableYouTubeTag = base.CreateObjectSet<TableYouTubeTag>("TableYouTubeTag");
                }
                return _TableYouTubeTag;
            }
        }
        private ObjectSet<TableYouTubeTag> _TableYouTubeTag;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TableDevice> TableDevice
        {
            get
            {
                if ((_TableDevice == null))
                {
                    _TableDevice = base.CreateObjectSet<TableDevice>("TableDevice");
                }
                return _TableDevice;
            }
        }
        private ObjectSet<TableDevice> _TableDevice;

        #endregion

        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TableYouTubeAttribute. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTableYouTubeAttribute(TableYouTubeAttribute tableYouTubeAttribute)
        {
            base.AddObject("TableYouTubeAttribute", tableYouTubeAttribute);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TableYouTubeKeyword. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTableYouTubeKeyword(TableYouTubeKeyword tableYouTubeKeyword)
        {
            base.AddObject("TableYouTubeKeyword", tableYouTubeKeyword);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TableYouTubeTag. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTableYouTubeTag(TableYouTubeTag tableYouTubeTag)
        {
            base.AddObject("TableYouTubeTag", tableYouTubeTag);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TableDevice. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTableDevice(TableDevice tableDevice)
        {
            base.AddObject("TableDevice", tableDevice);
        }

        #endregion

    }

    #endregion

    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OonzeModel", Name="TableDevice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableDevice : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TableDevice.
        /// </summary>
        /// <param name="id">Исходное значение свойства ID.</param>
        /// <param name="addressType">Исходное значение свойства AddressType.</param>
        /// <param name="groupID">Исходное значение свойства GroupID.</param>
        /// <param name="typeID">Исходное значение свойства TypeID.</param>
        /// <param name="saveSessions">Исходное значение свойства SaveSessions.</param>
        public static TableDevice CreateTableDevice(global::System.Int64 id, global::System.String addressType, global::System.Int64 groupID, global::System.Int64 typeID, global::System.Boolean saveSessions)
        {
            TableDevice tableDevice = new TableDevice();
            tableDevice.ID = id;
            tableDevice.AddressType = addressType;
            tableDevice.GroupID = groupID;
            tableDevice.TypeID = typeID;
            tableDevice.SaveSessions = saveSessions;
            return tableDevice;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InternalAddress
        {
            get
            {
                return _InternalAddress;
            }
            set
            {
                OnInternalAddressChanging(value);
                ReportPropertyChanging("InternalAddress");
                _InternalAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InternalAddress");
                OnInternalAddressChanged();
            }
        }
        private global::System.String _InternalAddress;
        partial void OnInternalAddressChanging(global::System.String value);
        partial void OnInternalAddressChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AddressType
        {
            get
            {
                return _AddressType;
            }
            set
            {
                OnAddressTypeChanging(value);
                ReportPropertyChanging("AddressType");
                _AddressType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AddressType");
                OnAddressTypeChanged();
            }
        }
        private global::System.String _AddressType;
        partial void OnAddressTypeChanging(global::System.String value);
        partial void OnAddressTypeChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.String _Port;
        partial void OnPortChanging(global::System.String value);
        partial void OnPortChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int64 _GroupID;
        partial void OnGroupIDChanging(global::System.Int64 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 TypeID
        {
            get
            {
                return _TypeID;
            }
            set
            {
                OnTypeIDChanging(value);
                ReportPropertyChanging("TypeID");
                _TypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TypeID");
                OnTypeIDChanged();
            }
        }
        private global::System.Int64 _TypeID;
        partial void OnTypeIDChanging(global::System.Int64 value);
        partial void OnTypeIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> OwnerID
        {
            get
            {
                return _OwnerID;
            }
            set
            {
                OnOwnerIDChanging(value);
                ReportPropertyChanging("OwnerID");
                _OwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OwnerID");
                OnOwnerIDChanged();
            }
        }
        private Nullable<global::System.Int64> _OwnerID;
        partial void OnOwnerIDChanging(Nullable<global::System.Int64> value);
        partial void OnOwnerIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP1
        {
            get
            {
                return _IP1;
            }
            set
            {
                OnIP1Changing(value);
                ReportPropertyChanging("IP1");
                _IP1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP1");
                OnIP1Changed();
            }
        }
        private global::System.String _IP1;
        partial void OnIP1Changing(global::System.String value);
        partial void OnIP1Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP2
        {
            get
            {
                return _IP2;
            }
            set
            {
                OnIP2Changing(value);
                ReportPropertyChanging("IP2");
                _IP2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP2");
                OnIP2Changed();
            }
        }
        private global::System.String _IP2;
        partial void OnIP2Changing(global::System.String value);
        partial void OnIP2Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP3
        {
            get
            {
                return _IP3;
            }
            set
            {
                OnIP3Changing(value);
                ReportPropertyChanging("IP3");
                _IP3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP3");
                OnIP3Changed();
            }
        }
        private global::System.String _IP3;
        partial void OnIP3Changing(global::System.String value);
        partial void OnIP3Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IP4
        {
            get
            {
                return _IP4;
            }
            set
            {
                OnIP4Changing(value);
                ReportPropertyChanging("IP4");
                _IP4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IP4");
                OnIP4Changed();
            }
        }
        private global::System.String _IP4;
        partial void OnIP4Changing(global::System.String value);
        partial void OnIP4Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryPort
        {
            get
            {
                return _SecondaryPort;
            }
            set
            {
                OnSecondaryPortChanging(value);
                ReportPropertyChanging("SecondaryPort");
                _SecondaryPort = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryPort");
                OnSecondaryPortChanged();
            }
        }
        private global::System.String _SecondaryPort;
        partial void OnSecondaryPortChanging(global::System.String value);
        partial void OnSecondaryPortChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryIP1
        {
            get
            {
                return _SecondaryIP1;
            }
            set
            {
                OnSecondaryIP1Changing(value);
                ReportPropertyChanging("SecondaryIP1");
                _SecondaryIP1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryIP1");
                OnSecondaryIP1Changed();
            }
        }
        private global::System.String _SecondaryIP1;
        partial void OnSecondaryIP1Changing(global::System.String value);
        partial void OnSecondaryIP1Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryIP2
        {
            get
            {
                return _SecondaryIP2;
            }
            set
            {
                OnSecondaryIP2Changing(value);
                ReportPropertyChanging("SecondaryIP2");
                _SecondaryIP2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryIP2");
                OnSecondaryIP2Changed();
            }
        }
        private global::System.String _SecondaryIP2;
        partial void OnSecondaryIP2Changing(global::System.String value);
        partial void OnSecondaryIP2Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryIP3
        {
            get
            {
                return _SecondaryIP3;
            }
            set
            {
                OnSecondaryIP3Changing(value);
                ReportPropertyChanging("SecondaryIP3");
                _SecondaryIP3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryIP3");
                OnSecondaryIP3Changed();
            }
        }
        private global::System.String _SecondaryIP3;
        partial void OnSecondaryIP3Changing(global::System.String value);
        partial void OnSecondaryIP3Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecondaryIP4
        {
            get
            {
                return _SecondaryIP4;
            }
            set
            {
                OnSecondaryIP4Changing(value);
                ReportPropertyChanging("SecondaryIP4");
                _SecondaryIP4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecondaryIP4");
                OnSecondaryIP4Changed();
            }
        }
        private global::System.String _SecondaryIP4;
        partial void OnSecondaryIP4Changing(global::System.String value);
        partial void OnSecondaryIP4Changed();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DataOwnerID
        {
            get
            {
                return _DataOwnerID;
            }
            set
            {
                OnDataOwnerIDChanging(value);
                ReportPropertyChanging("DataOwnerID");
                _DataOwnerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DataOwnerID");
                OnDataOwnerIDChanged();
            }
        }
        private Nullable<global::System.Guid> _DataOwnerID;
        partial void OnDataOwnerIDChanging(Nullable<global::System.Guid> value);
        partial void OnDataOwnerIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LocationAddressID
        {
            get
            {
                return _LocationAddressID;
            }
            set
            {
                OnLocationAddressIDChanging(value);
                ReportPropertyChanging("LocationAddressID");
                _LocationAddressID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationAddressID");
                OnLocationAddressIDChanged();
            }
        }
        private Nullable<global::System.Int64> _LocationAddressID;
        partial void OnLocationAddressIDChanging(Nullable<global::System.Int64> value);
        partial void OnLocationAddressIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> BillAddressID
        {
            get
            {
                return _BillAddressID;
            }
            set
            {
                OnBillAddressIDChanging(value);
                ReportPropertyChanging("BillAddressID");
                _BillAddressID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BillAddressID");
                OnBillAddressIDChanged();
            }
        }
        private Nullable<global::System.Int64> _BillAddressID;
        partial void OnBillAddressIDChanging(Nullable<global::System.Int64> value);
        partial void OnBillAddressIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> LocationID
        {
            get
            {
                return _LocationID;
            }
            set
            {
                OnLocationIDChanging(value);
                ReportPropertyChanging("LocationID");
                _LocationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LocationID");
                OnLocationIDChanged();
            }
        }
        private Nullable<global::System.Int64> _LocationID;
        partial void OnLocationIDChanging(Nullable<global::System.Int64> value);
        partial void OnLocationIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SaveSessions
        {
            get
            {
                return _SaveSessions;
            }
            set
            {
                OnSaveSessionsChanging(value);
                ReportPropertyChanging("SaveSessions");
                _SaveSessions = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaveSessions");
                OnSaveSessionsChanged();
            }
        }
        private global::System.Boolean _SaveSessions;
        partial void OnSaveSessionsChanging(global::System.Boolean value);
        partial void OnSaveSessionsChanged();

        #endregion

    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "FK_TableYouTubeAttributes_TableDevice", "TableYouTubeAttribute")]
        public EntityCollection<TableYouTubeAttribute> TableYouTubeAttribute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableYouTubeAttribute>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableYouTubeAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableYouTubeAttribute>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableYouTubeAttribute", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OonzeModel", Name="TableYouTubeAttribute")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableYouTubeAttribute : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TableYouTubeAttribute.
        /// </summary>
        /// <param name="id">Исходное значение свойства ID.</param>
        /// <param name="deviceID">Исходное значение свойства DeviceID.</param>
        public static TableYouTubeAttribute CreateTableYouTubeAttribute(global::System.Int64 id, global::System.Int64 deviceID)
        {
            TableYouTubeAttribute tableYouTubeAttribute = new TableYouTubeAttribute();
            tableYouTubeAttribute.ID = id;
            tableYouTubeAttribute.DeviceID = deviceID;
            return tableYouTubeAttribute;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 DeviceID
        {
            get
            {
                return _DeviceID;
            }
            set
            {
                OnDeviceIDChanging(value);
                ReportPropertyChanging("DeviceID");
                _DeviceID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceID");
                OnDeviceIDChanged();
            }
        }
        private global::System.Int64 _DeviceID;
        partial void OnDeviceIDChanging(global::System.Int64 value);
        partial void OnDeviceIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();

        #endregion

    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "TableYouTubeAttributeKeyword", "TableYouTubeKeyword")]
        public EntityCollection<TableYouTubeKeyword> TableYouTubeKeyword
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableYouTubeKeyword>("OonzeModel.TableYouTubeAttributeKeyword", "TableYouTubeKeyword");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableYouTubeKeyword>("OonzeModel.TableYouTubeAttributeKeyword", "TableYouTubeKeyword", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "TableYouTubeAttributeTag", "TableYouTubeTag")]
        public EntityCollection<TableYouTubeTag> TableYouTubeTag
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableYouTubeTag>("OonzeModel.TableYouTubeAttributeTag", "TableYouTubeTag");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableYouTubeTag>("OonzeModel.TableYouTubeAttributeTag", "TableYouTubeTag", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "FK_TableYouTubeAttributes_TableDevice", "TableDevice")]
        public TableDevice TableDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableDevice>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableDevice").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableDevice>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableDevice").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TableDevice> TableDeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TableDevice>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TableDevice>("OonzeModel.FK_TableYouTubeAttributes_TableDevice", "TableDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OonzeModel", Name="TableYouTubeKeyword")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableYouTubeKeyword : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TableYouTubeKeyword.
        /// </summary>
        /// <param name="id">Исходное значение свойства ID.</param>
        /// <param name="keyword">Исходное значение свойства Keyword.</param>
        public static TableYouTubeKeyword CreateTableYouTubeKeyword(global::System.Int64 id, global::System.String keyword)
        {
            TableYouTubeKeyword tableYouTubeKeyword = new TableYouTubeKeyword();
            tableYouTubeKeyword.ID = id;
            tableYouTubeKeyword.Keyword = keyword;
            return tableYouTubeKeyword;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Keyword
        {
            get
            {
                return _Keyword;
            }
            set
            {
                OnKeywordChanging(value);
                ReportPropertyChanging("Keyword");
                _Keyword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Keyword");
                OnKeywordChanged();
            }
        }
        private global::System.String _Keyword;
        partial void OnKeywordChanging(global::System.String value);
        partial void OnKeywordChanged();

        #endregion

    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "TableYouTubeAttributeKeyword", "TableYouTubeAttribute")]
        public EntityCollection<TableYouTubeAttribute> TableYouTubeAttribute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableYouTubeAttribute>("OonzeModel.TableYouTubeAttributeKeyword", "TableYouTubeAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableYouTubeAttribute>("OonzeModel.TableYouTubeAttributeKeyword", "TableYouTubeAttribute", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OonzeModel", Name="TableYouTubeTag")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TableYouTubeTag : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TableYouTubeTag.
        /// </summary>
        /// <param name="id">Исходное значение свойства ID.</param>
        /// <param name="tag">Исходное значение свойства Tag.</param>
        public static TableYouTubeTag CreateTableYouTubeTag(global::System.Int64 id, global::System.String tag)
        {
            TableYouTubeTag tableYouTubeTag = new TableYouTubeTag();
            tableYouTubeTag.ID = id;
            tableYouTubeTag.Tag = tag;
            return tableYouTubeTag;
        }

        #endregion

        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();

        #endregion

    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("OonzeModel", "TableYouTubeAttributeTag", "TableYouTubeAttribute")]
        public EntityCollection<TableYouTubeAttribute> TableYouTubeAttribute
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TableYouTubeAttribute>("OonzeModel.TableYouTubeAttributeTag", "TableYouTubeAttribute");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TableYouTubeAttribute>("OonzeModel.TableYouTubeAttributeTag", "TableYouTubeAttribute", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
